name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: 35c6db0a-87fe-42bb-a891-efdeb665eba0
          heroku_app_name: "wanghann"
          heroku_email: "nancy62924@gmail.com"
          usedocker: true
