
name: Push Container to Heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: 35c6db0a-87fe-42bb-a891-efdeb665eba0
      run: heroku container:login 
    - name: Build and push
      env:
        HEROKU_API_KEY: 35c6db0a-87fe-42bb-a891-efdeb665eba0
      run: heroku container:push -a wanghann web 
    - name: Release
      env:
        HEROKU_API_KEY: 35c6db0a-87fe-42bb-a891-efdeb665eba0
      run: heroku container:release -a wanghann web 
